config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'

  devise_for :admins, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy]
    resources :post_images, only: [:destroy]
    get 'homes/about', to: 'homes#about', as: 'admin_about'
  end

  scope module: :public do
    root to: "homes#top"
    get "homes/about", to: "homes#about"

    devise_for :users, controllers: {
      sessions: 'public/sessions'
    }

    resources :post_images, only: [:new, :create, :index, :show, :destroy] do
      resources :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end

    resources :users, only: [:show, :edit, :update]

    resource :map, only: [:show]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise authentication_keys: [:email] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

  # 1人のユーザーが1つの投稿に対して重複していいねを押せないようにする
  # user_idとpost_image_idのペアが一意である（重複しない）状態に制限
  validates :user_id, uniqueness: {scope: :post_image_id}
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord

    has_one_attached :image
    belongs_to :user
    has_many :post_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy

    validates :shop_name, presence: true
    validates :image, presence: true

    validates :address, presence: true
    geocoded_by :address
    after_validation :geocode

    def get_image
        unless image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        image
    end

    def favorited_by?(user)
        favorites.exists?(user_id: user.id)
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
  def index
      @users = User.all
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  layout 'admin'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    admin_dashboards_path # ログイン後にリダイレクトするパス
  end

  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path # ログアウト後にリダイレクトするパス
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to admin_dashboards_path, notice: 'ユーザーを削除しました。'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # サインイン後にどこに遷移するかを設定しているメソッド
  # (Deviseが用意しているメソッド) 7章
  before_action :authenticate_user!, except: [:top], unless: :admin_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  # 権限の設定

  private

  def configure_authentication
    # 現在のコントローラーがAdmin名前空間の下にあるかどうかを判定する。
    if admin_controller?
      # 管理者用の処理
      authenticate_admin!
    else
      # ユーザ用の処理
      authenticate_user! unless action_is_pubric?
    end
  end
 
  # 管理者用とユーザー用の認証処理を簡単に切り替えることができる
  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end

  # 特定のアクション（この例ではhomes#top）が認証が不要かどうかを判定します。
  def action_is_pubric?
    controller_name == "homes" && action_name == "top"
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboards/index.html.erb
<h1>全ユーザー一覧</h1>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.name %> - <%= user.email %>
      <%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: '本当に削除しますか？' } %> 
    </li>
  <% end %>
</ul>

app/views/post_images/_list.html.erb
<% post_images.each do |post_image| %>
    <div>
        <%= link_to post_image_path(post_image.id) do %>
            <%= image_tag post_image.get_image %>
        <% end %>
        <p>投稿ユーザー画像：<%= image_tag post_image.user.get_profile_image(100,100) %></p>
        <p>ショップ名：<%= post_image.shop_name %></p>
        <p>説明：<%= post_image.caption %></p>
        <p>ユーザーネーム：<%= post_image.user.name %></p>
        <p><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %></p>
    </div>
<% end %>
<%= paginate post_images %>

app/views/post_images/edit.html.erb
<h1>PostImages#edit</h1>
<p>Find me in app/views/post_images/edit.html.erb</p>

app/views/post_images/index.html.erb
<!-- 部分テンプレートで共通部分を呼び出す-->
<%= render "post_images/list", post_images: @post_images %>

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>

<% if @post_image.errors.any? %>
    <%= @post_image.errors.count %>件のエラーが発生しました
    <ul>
        <% @post_image.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

<%= form_with model: @post_image do |f| %>
    
    <h4>画像</h4>
    <%= f.file_field :image, accept: "image/*" %>
    
    <h4>ショップ名</h4>
    <%= f.text_field :shop_name %>

    <h4>説明</h4>
    <%= f.text_area :caption %>
    <%= f.submit "投稿" %>
    
<% end %>

app/views/post_images/show.html.erb
<div>
    <%= image_tag @post_image.get_image %>
    <p>ショップ名：<%= @post_image.shop_name %></p>
    <p>説明：<%= @post_image.caption %></p>
    
    <!-- @post_image・インスタンス変数（コントローラで設定された変数で、ビュー全体でアクセス可能） -->
    <p>ユーザアイコン：<%= image_tag @post_image.user.get_profile_image(100,100) %></p>
    <p>ユーザネーム：<%= @post_image.user.name %></p>
    <p>投稿日：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
    <% if @post_image.user == current_user %>
        <%= link_to "削除", post_image_path(@post_image), method: :delete %>
    <% end %>
    <% if @post_image.favorited_by?(current_user) %>
        <p>
            <%= link_to post_image_favorite_path(@post_image), method: :delete do%>
            ♥<%= @post_image.favorites.count %> いいね
            <% end %>
        </p>
        <% else %>
        <p>
            <%= link_to post_image_favorite_path(@post_image), method: :post do %>
            ♡<%= @post_image.favorites.count %> いいね
            <% end %>
        </p>
    <% end %>
</div>

<div>
    <p>コメント件数：<%= @post_image.post_comments.count %></p>
    <% @post_image.post_comments.each do |comment_item|%>
        <p><%= image_tag comment_item.user.get_profile_image(100,100)%></p>
        <%= comment_item.user.name %>
        <%= comment_item.created_at.strftime("%Y/%m/%d") %>
        <%= comment_item.comment %>
        <% if comment_item.user == current_user %>
            <%= link_to "削除", post_image_post_comment_path(comment_item.post_image, comment_item), method: :delete %>
        <% end %>
    <% end %>
</div>

<div>
    <%= form_with model: [@post_image, @post_comment] do |f| %>
        <%= f.text_area :comment, row: "5", placeholder: "コメントをここに" %>
        <%= f.submit "送信する" %>
    <% end %>
</div>